[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# These redirects ensure that all page routes get served by the Next.js app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Custom error page for client-side errors
[[redirects]]
  from = "/error"
  to = "/netlify-error.html"
  status = 200
